import { getHome } from "../utils/home";
import { registryEntries } from "../registry/entries";
import { resolvePath } from "../registry/resolve";
import type { ConfigEntry } from "../registry/types";
import { scanFile } from "../scan";
import { defaultEnv } from "../collectors/env";
import type { CollectorContext } from "../collectors/types";
import { collectHomebrew } from "../collectors/homebrew";
import { collectPackages } from "../collectors/packages";

export interface ChezmoiPlanItem {
  id: string;
  src: string;
  kind: "file" | "dir";
  encrypt: boolean;
  reason: string;
}

/**
 * Decide, per registry entry that exists on disk, whether chezmoi should add it
 * plain or `--encrypt`. Encrypts when the entry is high-sensitivity OR when the
 * file's content is detected as containing secrets — so a secret can never be
 * added in plaintext (the secret gate). Pure given its injected probes.
 */
export async function planChezmoiExport(
  entries: ConfigEntry[],
  home: string,
  fileExists: (p: string) => Promise<boolean>,
  hasSecret: (p: string) => Promise<boolean>,
): Promise<ChezmoiPlanItem[]> {
  const items: ChezmoiPlanItem[] = [];

  for (const entry of entries) {
    const src = resolvePath(entry, home);
    if (!src || !(await fileExists(src))) continue;

    const isDir = entry.kind.type === "dir";
    let encrypt = entry.sensitivity === "high";
    let reason = encrypt ? "sensitivity:high" : "plain";

    if (!encrypt && !isDir && (await hasSecret(src))) {
      encrypt = true;
      reason = "secret detected";
    }

    items.push({ id: entry.id, src, kind: isDir ? "dir" : "file", encrypt, reason });
  }

  return items;
}

/** A file is treated as secret-bearing if the scanner would redact or skip it. */
async function fileHasSecret(path: string): Promise<boolean> {
  const result = await scanFile(path);
  return !!result && (result.action === "redact" || result.action === "skip");
}

/**
 * SSH private keys in ~/.ssh, detected by content (a private-key header) rather than
 * filename — so it catches id_ed25519, id_rsa, custom *.key, etc. Skips .pub files.
 */
export async function findSshPrivateKeys(
  home: string,
  listDir: (p: string) => Promise<string[]>,
  isPrivateKey: (p: string) => Promise<boolean>,
): Promise<string[]> {
  const dir = `${home}/.ssh`;
  const keys: string[] = [];
  for (const name of await listDir(dir)) {
    if (name.endsWith(".pub")) continue;
    const path = `${dir}/${name}`;
    if (await isPrivateKey(path)) keys.push(path);
  }
  return keys.sort();
}

async function isSshPrivateKey(path: string): Promise<boolean> {
  const result = await scanFile(path);
  return (
    !!result && result.findings.some((f) => f.pattern.id === "private-key-pem" || f.pattern.id === "pgp-private-key")
  );
}

export interface InstallManifest {
  brewfile?: string;
  nodeVersions?: string[];
  bunGlobals?: string[];
  npmGlobals?: string[];
  pnpmGlobals?: string[];
}

/**
 * A chezmoi `run_onchange_` script that reinstalls packages on `chezmoi apply` — so a fresh
 * machine gets brew formulae/casks, node versions, and global packages, not just config files.
 * Every step is command-guarded and `|| true` so a missing tool never aborts apply.
 */
export function buildPackageInstallScript(m: InstallManifest): string {
  const lines = [
    "#!/bin/bash",
    "# Generated by `dotfiles chezmoi-export`. chezmoi re-runs this on apply when it changes.",
    "set -uo pipefail",
    "",
  ];

  if (m.brewfile?.trim()) {
    lines.push(
      "if command -v brew >/dev/null 2>&1; then",
      "  brew bundle --file=/dev/stdin <<'BREWFILE'",
      m.brewfile.trim(),
      "BREWFILE",
      "fi",
      "",
    );
  }

  const versions = (m.nodeVersions ?? []).filter((v) => v && v !== "system");
  if (versions.length) {
    lines.push("if command -v fnm >/dev/null 2>&1; then");
    for (const v of versions) lines.push(`  fnm install ${v} || true`);
    lines.push("fi", "");
  }

  const block = (tool: string, add: string, pkgs?: string[]) => {
    if (!pkgs?.length) return;
    lines.push(`if command -v ${tool} >/dev/null 2>&1; then`, `  ${add} ${pkgs.join(" ")} || true`, "fi", "");
  };
  block("bun", "bun add -g", m.bunGlobals);
  block("pnpm", "pnpm add -g", m.pnpmGlobals);
  block("npm", "npm install -g", m.npmGlobals);

  return `${lines.join("\n").trimEnd()}\n`;
}

/** gnupg is worth carrying only if it holds real secret keys (private-keys-v1.d/*.key); otherwise
 * `chezmoi add ~/.gnupg` just captures lock-file/runtime cruft. */
export async function gnupgHasSecretKeys(home: string, listDir: (p: string) => Promise<string[]>): Promise<boolean> {
  return (await listDir(`${home}/.gnupg/private-keys-v1.d`)).some((f) => f.endsWith(".key"));
}

async function gatherInstallManifest(ctx: CollectorContext): Promise<InstallManifest> {
  const brew = await collectHomebrew(ctx);
  const pkgs = await collectPackages(ctx);
  const raws = (id: string) => (pkgs[id]?.items ?? []).map((i) => i.raw);
  return {
    brewfile: brew["apps.brew.bundle"]?.content ?? undefined,
    nodeVersions: (pkgs["packages.node.fnm"]?.items ?? []).map((i) => i.columns[0]),
    bunGlobals: raws("packages.bun.global"),
    npmGlobals: raws("packages.npm.global"),
    pnpmGlobals: raws("packages.pnpm.global"),
  };
}

export async function chezmoiExport(args: string[]) {
  const apply = args.includes("--apply");
  const home = getHome();
  const plan = await planChezmoiExport(registryEntries, home, defaultEnv.fileExists, fileHasSecret);

  // SSH private keys aren't a single registry path (filenames vary) — sweep ~/.ssh by content.
  for (const key of await findSshPrivateKeys(home, defaultEnv.listDir, isSshPrivateKey)) {
    if (!plan.some((p) => p.src === key)) {
      plan.push({ id: "ssh.key", src: key, kind: "file", encrypt: true, reason: "ssh private key" });
    }
  }

  // Drop the gnupg dir unless it has real secret keys — avoids carrying lock-file/runtime cruft.
  if (!(await gnupgHasSecretKeys(home, defaultEnv.listDir))) {
    const i = plan.findIndex((p) => p.id === "secrets.gnupg");
    if (i >= 0) plan.splice(i, 1);
  }

  if (plan.length === 0) {
    console.log("Nothing to export — no managed configs found on this machine.");
    return;
  }

  const encrypted = plan.filter((p) => p.encrypt).length;
  console.log(`chezmoi-export plan — ${plan.length} path(s), ${encrypted} encrypted:\n`);
  for (const item of plan) {
    console.log(`  ${item.encrypt ? "🔒 add --encrypt" : "   add          "}  ${item.src}  (${item.reason})`);
  }

  if (!apply) {
    console.log("\nDry-run. Re-run with --apply to execute (requires chezmoi + a configured age key).");
    return;
  }

  let chezmoiOk = false;
  try {
    chezmoiOk = !!(await defaultEnv.run(["chezmoi", "--version"])).trim();
  } catch {}
  if (!chezmoiOk) {
    console.error("\nchezmoi not found. Install it (brew install chezmoi) and configure age encryption first.");
    process.exitCode = 1;
    return;
  }

  console.log("");
  for (const item of plan) {
    const cmd = item.encrypt ? ["chezmoi", "add", "--encrypt", item.src] : ["chezmoi", "add", item.src];
    try {
      await defaultEnv.run(cmd);
      console.log(`  ✔ ${item.encrypt ? "encrypted " : ""}${item.src}`);
    } catch (error) {
      console.error(`  ✗ ${item.src}: ${error}`);
    }
  }

  // Generate a run_onchange install script so `chezmoi apply` also reinstalls packages.
  try {
    const script = buildPackageInstallScript(await gatherInstallManifest({ redact: false, home }));
    const sourcePath = (await defaultEnv.run(["chezmoi", "source-path"])).trim();
    if (sourcePath) {
      await Bun.write(`${sourcePath}/run_onchange_install-packages.sh`, script);
      console.log("  ✔ run_onchange_install-packages.sh (brew + node + global packages)");
    }
  } catch (error) {
    console.error(`  ✗ install script: ${error}`);
  }

  console.log("\nDone. Review with `chezmoi diff`, then commit your private chezmoi source repo.");
}
