import { redactSshConfig, redactNpmTokens } from "../utils/redact";
import type { ConfigEntry } from "./types";

export const registryEntries: ConfigEntry[] = [
  // === AI: Claude ===
  {
    id: "ai.claude.settings",
    name: "Claude Settings",
    paths: {
      darwin: "~/.claude/settings.json",
      linux: "~/.claude/settings.json",
      win32: "%USERPROFILE%/.claude/settings.json",
    },
    category: "ai",
    kind: { type: "json-extract", fields: ["permissions", "enabledPlugins"] },
    backupDest: "ai/claude/settings.json",
    sensitivity: "low",
  },
  {
    id: "ai.claude.skills",
    name: "Claude Skills",
    paths: { darwin: "~/.claude/skills", linux: "~/.claude/skills", win32: "%USERPROFILE%/.claude/skills" },
    category: "ai",
    kind: { type: "dir" },
    backupDest: "ai/claude/skills",
    sensitivity: "low",
  },
  {
    id: "ai.claude.md",
    name: "CLAUDE.md",
    paths: { darwin: "~/.claude/CLAUDE.md", linux: "~/.claude/CLAUDE.md", win32: "%USERPROFILE%/.claude/CLAUDE.md" },
    category: "ai",
    kind: { type: "file" },
    backupDest: "ai/claude/CLAUDE.md",
    sensitivity: "low",
  },

  // === AI: Cursor ===
  {
    id: "ai.cursor.mcp",
    name: "Cursor MCP Config",
    paths: { darwin: "~/.cursor/mcp.json", linux: "~/.cursor/mcp.json", win32: "%USERPROFILE%/.cursor/mcp.json" },
    category: "ai",
    kind: { type: "file" },
    backupDest: "ai/cursor/mcp.json",
    sensitivity: "low",
  },
  {
    id: "ai.cursor.skills",
    name: "Cursor Skills",
    paths: { darwin: "~/.cursor/skills", linux: "~/.cursor/skills", win32: "%USERPROFILE%/.cursor/skills" },
    category: "ai",
    kind: { type: "dir" },
    backupDest: "ai/cursor/skills",
    sensitivity: "low",
  },

  // === AI: Gemini ===
  {
    id: "ai.gemini.settings",
    name: "Gemini Settings",
    paths: {
      darwin: "~/.gemini/settings.json",
      linux: "~/.gemini/settings.json",
      win32: "%USERPROFILE%/.gemini/settings.json",
    },
    category: "ai",
    kind: { type: "json-extract", fields: [] },
    backupDest: "ai/gemini/settings.json",
    sensitivity: "low",
  },
  {
    id: "ai.gemini.skills",
    name: "Gemini Skills",
    paths: { darwin: "~/.gemini/skills", linux: "~/.gemini/skills", win32: "%USERPROFILE%/.gemini/skills" },
    category: "ai",
    kind: { type: "dir" },
    backupDest: "ai/gemini/skills",
    sensitivity: "low",
  },
  {
    id: "ai.gemini.md",
    name: "GEMINI.md",
    paths: { darwin: "~/.gemini/GEMINI.md", linux: "~/.gemini/GEMINI.md", win32: "%USERPROFILE%/.gemini/GEMINI.md" },
    category: "ai",
    kind: { type: "file" },
    backupDest: "ai/gemini/GEMINI.md",
    sensitivity: "low",
  },

  // === AI: Windsurf ===
  {
    id: "ai.windsurf.mcp",
    name: "Windsurf MCP Config",
    paths: {
      darwin: "~/.codeium/windsurf/mcp_config.json",
      linux: "~/.codeium/windsurf/mcp_config.json",
      win32: "%USERPROFILE%/.codeium/windsurf/mcp_config.json",
    },
    category: "ai",
    kind: { type: "file" },
    backupDest: "ai/windsurf/mcp_config.json",
    sensitivity: "low",
  },
  {
    id: "ai.windsurf.skills",
    name: "Windsurf Skills",
    paths: {
      darwin: "~/.codeium/windsurf/skills",
      linux: "~/.codeium/windsurf/skills",
      win32: "%USERPROFILE%/.codeium/windsurf/skills",
    },
    category: "ai",
    kind: { type: "dir" },
    backupDest: "ai/windsurf/skills",
    sensitivity: "low",
  },

  // === Shell ===
  {
    id: "shell.zshrc",
    name: ".zshrc",
    paths: { darwin: "~/.zshrc", linux: "~/.zshrc" },
    category: "shell",
    kind: { type: "file" },
    backupDest: "shell/.zshrc",
    sensitivity: "low",
  },
  {
    id: "shell.zprofile",
    name: ".zprofile",
    paths: { darwin: "~/.zprofile", linux: "~/.zprofile" },
    category: "shell",
    kind: { type: "file" },
    backupDest: "shell/.zprofile",
    sensitivity: "low",
  },
  {
    id: "shell.zshenv",
    name: ".zshenv",
    paths: { darwin: "~/.zshenv", linux: "~/.zshenv" },
    category: "shell",
    kind: { type: "file" },
    backupDest: "shell/.zshenv",
    sensitivity: "low",
  },
  {
    id: "shell.bash_profile",
    name: ".bash_profile",
    paths: { darwin: "~/.bash_profile", linux: "~/.bash_profile" },
    category: "shell",
    kind: { type: "file" },
    backupDest: "shell/.bash_profile",
    sensitivity: "low",
  },
  {
    id: "shell.bashrc",
    name: ".bashrc",
    paths: { darwin: "~/.bashrc", linux: "~/.bashrc" },
    category: "shell",
    kind: { type: "file" },
    backupDest: "shell/.bashrc",
    sensitivity: "low",
  },

  // === Git ===
  {
    id: "git.config",
    name: ".gitconfig",
    paths: { darwin: "~/.gitconfig", linux: "~/.gitconfig", win32: "%USERPROFILE%/.gitconfig" },
    category: "git",
    kind: { type: "file" },
    backupDest: "git/.gitconfig",
    sensitivity: "low",
  },
  {
    id: "git.ignore",
    name: ".gitignore_global",
    paths: { darwin: "~/.gitignore_global", linux: "~/.gitignore_global", win32: "%USERPROFILE%/.gitignore_global" },
    category: "git",
    kind: { type: "file" },
    backupDest: "git/.gitignore_global",
    sensitivity: "low",
  },
  {
    id: "gh.config",
    name: "GitHub CLI Config",
    paths: {
      darwin: "~/.config/gh/config.yml",
      linux: "~/.config/gh/config.yml",
      win32: "%APPDATA%/GitHub CLI/config.yml",
    },
    category: "git",
    kind: { type: "file" },
    backupDest: "git/gh/config.yml",
    sensitivity: "low",
  },

  // === Editors ===
  {
    id: "editor.zed",
    name: "Zed Settings",
    paths: {
      darwin: "~/.config/zed/settings.json",
      linux: "~/.config/zed/settings.json",
      win32: "%APPDATA%/Zed/settings.json",
    },
    category: "editor",
    kind: { type: "file" },
    backupDest: "editor/zed/settings.json",
    sensitivity: "low",
  },
  {
    id: "editor.cursor",
    name: "Cursor Settings",
    paths: {
      darwin: "~/Library/Application Support/Cursor/User/settings.json",
      linux: "~/.config/Cursor/User/settings.json",
      win32: "%APPDATA%/Cursor/User/settings.json",
    },
    category: "editor",
    kind: { type: "file" },
    backupDest: "editor/cursor/settings.json",
    sensitivity: "low",
  },
  {
    id: "editor.nvim",
    name: "Neovim Config",
    paths: {
      darwin: "~/.config/nvim/init.lua",
      linux: "~/.config/nvim/init.lua",
      win32: "%USERPROFILE%/AppData/Local/nvim/init.lua",
    },
    category: "editor",
    kind: { type: "file" },
    backupDest: "editor/nvim/init.lua",
    sensitivity: "low",
  },
  {
    id: "editor.vimrc",
    name: ".vimrc",
    paths: { darwin: "~/.vimrc", linux: "~/.vimrc", win32: "%USERPROFILE%/_vimrc" },
    category: "editor",
    kind: { type: "file" },
    backupDest: "editor/.vimrc",
    sensitivity: "low",
  },

  // === Terminal ===
  {
    id: "terminal.p10k",
    name: ".p10k.zsh",
    paths: { darwin: "~/.p10k.zsh", linux: "~/.p10k.zsh" },
    category: "terminal",
    kind: { type: "file", metadata: true },
    backupDest: "terminal/.p10k.zsh",
    sensitivity: "low",
  },
  {
    id: "terminal.tmux",
    name: ".tmux.conf",
    paths: { darwin: "~/.tmux.conf", linux: "~/.tmux.conf" },
    category: "terminal",
    kind: { type: "file" },
    backupDest: "terminal/.tmux.conf",
    sensitivity: "low",
  },

  // === SSH ===
  {
    id: "ssh.config",
    name: "SSH Config",
    paths: { darwin: "~/.ssh/config", linux: "~/.ssh/config", win32: "%USERPROFILE%/.ssh/config" },
    category: "ssh",
    kind: { type: "file" },
    backupDest: "ssh/config",
    sensitivity: "medium",
    redact: redactSshConfig,
  },

  // === npm ===
  {
    id: "npm.config",
    name: ".npmrc",
    paths: { darwin: "~/.npmrc", linux: "~/.npmrc", win32: "%USERPROFILE%/.npmrc" },
    category: "npm",
    kind: { type: "file" },
    backupDest: "npm/.npmrc",
    sensitivity: "high",
    redact: redactNpmTokens,
  },

  // === Bun ===
  {
    id: "bun.config",
    name: ".bunfig.toml",
    paths: { darwin: "~/.bunfig.toml", linux: "~/.bunfig.toml", win32: "%USERPROFILE%/.bunfig.toml" },
    category: "bun",
    kind: { type: "file" },
    backupDest: "bun/.bunfig.toml",
    sensitivity: "low",
  },

  // === Cloud CLIs ===
  {
    id: "cloud.aws.config",
    name: "AWS CLI config",
    paths: { darwin: "~/.aws/config", linux: "~/.aws/config", win32: "%USERPROFILE%/.aws/config" },
    category: "cloud",
    kind: { type: "file" },
    backupDest: "cloud/aws/config",
    sensitivity: "medium",
  },
  {
    id: "cloud.aws.credentials",
    name: "AWS CLI credentials",
    paths: { darwin: "~/.aws/credentials", linux: "~/.aws/credentials", win32: "%USERPROFILE%/.aws/credentials" },
    category: "cloud",
    kind: { type: "file" },
    backupDest: "cloud/aws/credentials",
    sensitivity: "high",
  },
  {
    id: "cloud.gcloud.configurations",
    name: "gcloud configurations",
    paths: { darwin: "~/.config/gcloud/configurations", linux: "~/.config/gcloud/configurations" },
    category: "cloud",
    kind: { type: "dir" },
    backupDest: "cloud/gcloud/configurations",
    sensitivity: "medium",
  },
  {
    id: "cloud.kube.config",
    name: "kubeconfig",
    paths: { darwin: "~/.kube/config", linux: "~/.kube/config", win32: "%USERPROFILE%/.kube/config" },
    category: "cloud",
    kind: { type: "file" },
    backupDest: "cloud/kube/config",
    sensitivity: "high",
  },
  {
    id: "cloud.docker.config",
    name: "Docker config",
    paths: {
      darwin: "~/.docker/config.json",
      linux: "~/.docker/config.json",
      win32: "%USERPROFILE%/.docker/config.json",
    },
    category: "cloud",
    kind: { type: "file" },
    backupDest: "cloud/docker/config.json",
    sensitivity: "high",
  },

  // === Secrets (carried encrypted, never plaintext) ===
  {
    id: "secrets.gnupg",
    name: "GnuPG home",
    paths: { darwin: "~/.gnupg", linux: "~/.gnupg" },
    category: "secrets",
    kind: { type: "dir" },
    backupDest: "secrets/gnupg",
    sensitivity: "high",
  },
];
